services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: lstm-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    # restart: unless-stopped
