name: lstm-pipeline
channels:
  - conda-forge/label/main
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - tensorflow
  - joblib
  - pyarrow
  - fastapi
  - uvicorn
  - pydantic
  - python-dotenv
  - requests
  - pip
  - pip:
      - boto3
      - scikit-learn==1.3.2
      - yfinance
      - alpha_vantage
