name: lstm-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mamba
  - pip
  - numpy=1.26.4
  - scikit-learn=1.3.2
  - pandas=2.2.2
  - joblib=1.3.2
  - boto3=1.34.103
  - pyarrow=15.0.2
  - pip:
      - tensorflow==2.15.0
      - fastapi==0.115.1
      - uvicorn[standard]==0.34.1
      - pydantic==2.11.5
      - yfinance==0.2.37
      - python-dotenv==1.0.1
      - requests
      - alpha_vantage
