name: lstm-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn=1.2.2
  - pandas  # automaticamente já traz numpy e as dependências C
  - numpy
  - joblib=1.3.2
  - pip
  - pip:
      - boto3==1.34.103
      - fastapi==0.115.1
      - uvicorn[standard]==0.34.1
      - pydantic==2.11.5
      - python-dotenv==1.0.1
      - yfinance==0.2.37
      - alpha_vantage==2.3.1
      - requests==2.32.3
